### ISSUE TITLE
Safe stack doesn't build for azure

### ISSUE THREAD

**Issue by OnurGumus** [SAFE-Stack/SAFE-template#102]
I have created the template with :

` dotnet new SAFE --deploy azure`

next if I run build I get the below error:

```

Paket version 5.171.0
paket.dependencies and paket.lock are out of sync in D:\Projects\FSharp\Safe.
Please run 'paket install' or 'paket update' to recompute the paket.lock file.
Changes were detected for Build/Microsoft.Azure.Management.ResourceManager.Fluent
    - SettingsChanged
Starting full restore process.
Performance:
 - Disk IO: 11 milliseconds
 - Runtime: 8 seconds
This runner is now obsolete with FAKE 5, please upgrade to the new .Net Core runner. See https://fake.build/fake-migrate-to-fake-5.html
To remove this warning you can append the '--removeLegacyFakeWarning' argument or set the 'FAKE_NO_LEGACY_WARNING' environment variable to 'true'
build.fsx(111,17): error FS0010: Unexpected start of structured construct in expression

CACHING WARNING
this might happen after Updates...
please open a issue on FAKE and /cc @matthid ONLY IF this happens reproducibly)

Error: System.Exception: We could not find a type similar to '<StartupCode$FSI_0001>.$FSI_0001_Build$fsx' containing a 'main@' method in the cached assembly (D:\Projects\FSharp\Safe/.fake/build.fsx_2AF196CF.dll)!
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Fake.FSIHelper.runScriptCached(Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in D:\a\1\s\src\legacy\FakeLib\FSIHelper.fs:line 360
   at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages(Boolean printDetails, FsiArgs _arg1, IEnumerable`1 env, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache) in D:\a\1\s\src\legacy\FakeLib\FSIHelper.fs:line 629
Unable to access D:\Projects\FSharp\Safe\.fake\build.fsx_2AF196CF.dll
FsiEvaluationException:

Error:

        build.fsx(111,17): error FS0010: Unexpected start of structured construct in expression



Output: [Loading D:\Projects\FSharp\Safe\.paket\load\netcoreapp2.1\Build\build.group.fsx
         Loading D:\Projects\FSharp\Safe\paket-files/build/CompositionalIT/fshelpers/src/FsHelpers/ArmHelper/ArmHelper.fs
         Loading D:\Projects\FSharp\Safe\build.fsx]


Input: D:\Projects\FSharp\Safe\build.fsx
\Arguments:
  C:\fsi.exe

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been printed in the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res)
   at Yaaf.FSharp.Scripting.Helper.evalScript@1325.Invoke(String arg00) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1325
   at Yaaf.FSharp.Scripting.Helper.save_@1298-2.Invoke(Unit unitVar0) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1299
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1269[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1276
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1298
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1306
   at Yaaf.FSharp.Scripting.Helper.session@1328.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String path) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1330
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in D:\a\1\s\src\legacy\FakeLib\FSIHelper.fs:line 565
build.fsx(111,17): error FS0010: Unexpected start of structured construct in expression


```

**Comment by theimowski** [comment]
actually it was me who spoilt the build script with indentation normalization. Fix is undergoing in 0.21.3. Thanks for reporting!
