### ISSUE TITLE
Build Error for App.js

### ISSUE THREAD

**Issue by brase** [SAFE-Stack/SAFE-template#13]
Hi,

I just tried the template (on Windows).
Steps to reproduce:

```
mkdir safeTest1
cd safeTest1
dotnet new -i SAFE.Template
dotnet new SAFE
build.cmd
```

Then I get the following error while compiling the App.js file:

```
C:\Users\brase\AppData\Local\dotnetcore\dotnet.exe fable webpack -- -p
Fable (1.2.4) daemon started on port 61225
CWD: C:\Users\brase\code\fs\safeTest\src\Client
cmd /C node "C:\Users\brase\code\fs\safeTest\node_modules\webpack\bin\webpack.js" -p
Bundling for production...
Parsing ./Client.fsproj...
fable: Compiled Client.fsproj
ERROR: Method not found: 'Void Fable.AST.Fable.File..ctor(System.String, Fable.AST.Fable.Entity, Microsoft.FSharp.Collections.FSharpList`1<Fable.AST.Fable.Declaration>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpSet`1<System.String>>)'.
   at Fable.FSharp2Fable.Compiler.transformFile(ICompiler com, ICompilerState state, FSharpCheckProjectResults checkedProject, String fileName)
   at Fable.CLI.StateUtil.compile(Compiler com, Project project, String filePath)
   at Fable.CLI.StateUtil.loop@222-8.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)
Hash: 001ce6c433228fac9f24
Version: webpack 3.7.1
Time: 10901ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.15 kB       0  [emitted]  main
bundle.js.map  7.31 kB       0  [emitted]  main
   [0] ./Client.fsproj 25 bytes {0} [built]
   [1] ./App.fs 454 bytes {0} [built] [failed] [1 error]

ERROR in ./App.fs
Module build failed: Error: Method not found: 'Void Fable.AST.Fable.File..ctor(System.String, Fable.AST.Fable.Entity, Microsoft.FSharp.Collections.FSharpList`1<Fable.AST.Fable.Declaration>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Collections.FSharpSet`1<System.String>>)'.
    at Loader.fableUtils.client.send.then.r (C:\Users\brase\code\fs\safeTest\node_modules\fable-loader\index.js:67:22)
    at <anonymous>
 @ ./Client.fsproj 1:0-25
Closing Fable daemon...
Running build failed.
Error:
System.Exception: 'C:\Users\brase\AppData\Local\dotnetcore\dotnet.exe fable webpack -- -p' failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.run(String cmd, String args, String workingDir) in C:\Users\brase\code\fs\safeTest\build.fsx:line 28
   at FSI_0005.Build.clo@45-3.Invoke(Unit unitVar0) in C:\Users\brase\code\fs\safeTest\build.fsx:line 46
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0002597
InstallDotNetCore   00:00:42.1954222
InstallClient       00:00:17.3826909
Build               Failure
Total:              00:01:20.4162254
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: 'C:\Users\brase\AppData\Local\dotnetcore\dotnet.exe fable webpack -- -p' failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.run(String cmd, String args, String workingDir) in C:\Users\brase\code\fs\safeTest\build.fsx:line 28
   at FSI_0005.Build.clo@45-3.Invoke(Unit unitVar0) in C:\Users\brase\code\fs\safeTest\build.fsx:line 46
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

I am using the following dotnet version:

```
▶ dotnet --version
2.1.1-preview-007165
~\code\fs\safeTest                
▶ dotnet --info
.NET Command Line Tools (2.1.1-preview-007165)

Product Information:
 Version:            2.1.1-preview-007165
 Commit SHA-1 hash:  a4d1a8e0bb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1-preview-007165\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

```

**Comment by theimowski** [comment]
@alfonsogarciacaro can you help here?

**Comment by idursun** [comment]
It seems dotnet-fable version is old. Updating it to the latest version fixes the problem.
`.\.paket\paket.exe update dotnet-fable`

**Comment by theimowski** [comment]
I updated all paket dependencies - can you please try latest version?

**Comment by brase** [comment]
Yes! It works now. Thank You!
