### ISSUE TITLE
Following quick start fails

### ISSUE THREAD

**Issue by jeremy-sen-of-soren** [SAFE-Stack/SAFE-template#249]
When I follow the SAFE quick start directions to create a project with the SAFE template it fails. I don't know if these two things are related but during the build step there is an error in events.js. When I point my web browser at 0.0.0.0:8085 or localhost 0.0.0.0:8085 or 0.0.0.:8085/index.html, the server reports 404 not found, and nothing shows up in the web page. Here is my command window to reproduce:

Microsoft Windows [Version 10.0.16299.1029]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\projects>dotnet --version
2.2.106

C:\projects>fake --version
FAKE 5 - F# Make (5.13.0) (this line is written to standard error, see https://github.com/fsharp/FAKE/issues/2066)
FakePath: C:\Users\jsorens2\.dotnet\tools\.store\fake-cli\5.13.0\fake-cli\5.13.0\tools\netcoreapp2.1\any\Fake.Runtime.dll
Paket.Core: 5.203.0

C:\projects>paket --version
Paket version 5.203.2

C:\projects>node --version
v10.14.1

C:\projects>yarn --version
1.15.2

C:\projects>mkdir safe_test

C:\projects>cd safe_test

C:\projects\safe_test>dotnet new -i SAFE.Template
  Restoring packages for C:\Users\jsorens2\.templateengine\dotnetcli\v2.2.106\scratch\restore.csproj...
  Installing SAFE.Template 1.0.1.
  Generating MSBuild file C:\Users\jsorens2\.templateengine\dotnetcli\v2.2.106\scratch\obj\restore.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\jsorens2\.templateengine\dotnetcli\v2.2.106\scratch\obj\restore.csproj.nuget.g.targets.
  Restore completed in 2.34 sec for C:\Users\jsorens2\.templateengine\dotnetcli\v2.2.106\scratch\restore.csproj.

Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.

Templates                                         Short Name         Language          Tags                             
------------------------------------------------------------------------------------------------------------------------------
Console Application                               console            [C#], F#, VB      Common/Console                   
Class library                                     classlib           [C#], F#, VB      Common/Library                   
SAFE-Stack Web App v1.0.1                         SAFE               F#                F#/Web/Suave/Fable/Elmish/Giraffe/Bulma
Unit Test Project                                 mstest             [C#], F#, VB      Test/MSTest                      
NUnit 3 Test Project                              nunit              [C#], F#, VB      Test/NUnit                       
NUnit 3 Test Item                                 nunit-test         [C#], F#, VB      Test/NUnit                       
xUnit Test Project                                xunit              [C#], F#, VB      Test/xUnit                       
Razor Page                                        page               [C#]              Web/ASP.NET                      
MVC ViewImports                                   viewimports        [C#]              Web/ASP.NET                      
MVC ViewStart                                     viewstart          [C#]              Web/ASP.NET                      
ASP.NET Core Empty                                web                [C#], F#          Web/Empty                        
ASP.NET Core Web App (Model-View-Controller)      mvc                [C#], F#          Web/MVC                          
ASP.NET Core Web App                              webapp             [C#]              Web/MVC/Razor Pages              
ASP.NET Core with Angular                         angular            [C#]              Web/MVC/SPA                      
ASP.NET Core with React.js                        react              [C#]              Web/MVC/SPA                      
ASP.NET Core with React.js and Redux              reactredux         [C#]              Web/MVC/SPA                      
Razor Class Library                               razorclasslib      [C#]              Web/Razor/Library/Razor Class Library
ASP.NET Core Web API                              webapi             [C#], F#          Web/WebAPI                       
global.json file                                  globaljson                           Config                           
NuGet Config                                      nugetconfig                          Config                           
Web Config                                        webconfig                            Config                           
Solution File                                     sln                                  Solution                         

Examples:
    dotnet new mvc --auth Individual
    dotnet new --help

C:\projects\safe_test>dotnet new SAFE
The template "SAFE-Stack Web App v1.0.1" was created successfully.

C:\projects\safe_test>fake build --target run
Extracted Paket.Restore.targets to: C:\projects\safe_test\.paket\Paket.Restore.targets
Starting full restore process.
run run
Building project with version: LocalBuild
Shortened DependencyGraph for Target Run:
<== Run
   <== InstallClient
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - InstallClient
Group - 3
  - Run
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0105330
Starting target 'InstallClient'
Node version:
C:\projects\safe_test> "C:\Program Files\nodejs\node.exe" --version (In: false, Out: false, Err: false)
v10.14.1
Yarn version:
C:\projects\safe_test> "C:\Program Files (x86)\Yarn\bin\yarn.cmd" --version (In: false, Out: false, Err: false)
1.15.2
C:\projects\safe_test> "C:\Program Files (x86)\Yarn\bin\yarn.cmd" install --frozen-lockfile (In: false, Out: false, Err: false)
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 7.72s.
C:\projects\safe_test\src\Client> "C:\Program Files\dotnet\dotnet.EXE" restore (In: false, Out: false, Err: false)
  Restoring packages for C:\projects\safe_test\src\Client\Client.fsproj...
  Generating MSBuild file C:\projects\safe_test\src\Client\obj\Client.fsproj.nuget.g.props.
  Generating MSBuild file C:\projects\safe_test\src\Client\obj\Client.fsproj.nuget.g.targets.
  Restore completed in 233.38 ms for C:\projects\safe_test\src\Client\Client.fsproj.
Finished (Success) 'InstallClient' in 00:00:10.0819315
Starting target 'Run'
C:\projects\safe_test> "C:\Program Files (x86)\Yarn\bin\yarn.cmd" webpack-dev-server (In: false, Out: false, Err: false)
C:\projects\safe_test\src\Server> "C:\Program Files\dotnet\dotnet.EXE" watch run (In: false, Out: false, Err: false)
yarn run v1.15.2
$ C:\projects\safe_test\node_modules\.bin\webpack-dev-server
watch : Started
Bundling for development...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\jsorens2\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: C:\projects\safe_test\src\Server
Now listening on: http://0.0.0.0:8085
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://0.0.0.0:8085/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 124.7212ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8085/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.7866ms 404
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8085/index.html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.4968ms 404
Application is shutting down...
watch : Shutdown requested. Press Ctrl+C again to force exit.
Gracefully shutting down..
Press ctrl+c again to force quit
watch : Exited
Finished (Failed) 'Run' in 00:01:31.4632127

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target          Duration
------          --------
Clean           00:00:00.0027274
InstallClient   00:00:10.0806836
Run             00:01:31.4618498   (Process exit code '1' <> 0. Command Line: C:\Program Files (x86)\Yarn\bin\yarn.cmd webpack-dev-server)
Total:          00:01:41.7091279
Status:         Failure
---------------------------------------------------------------------
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.203.0' at the top of your dependencies file (C:\projects\safe_test\paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Performance:
 - Cli parsing: 242 milliseconds
 - Packages: 630 milliseconds
   - Disk IO: 87 milliseconds
   - Creating Runtime Graph: 115 milliseconds
   - Retrieve Assembly List: 584 milliseconds
 - Script compiling: 4 seconds
 - Script analyzing: 240 milliseconds
 - Script running: 1 minute, 42 seconds
 - Script cleanup: 7 milliseconds
 - Runtime: 1 minute, 48 seconds

C:\projects\safe_test>

**Comment by jeremy-sen-of-soren** [comment]
Yeah that was it. I followed your instructions and got the sample to work.
