### ISSUE TITLE
Get the template building with devops

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#296]
I've started work on getting the build working in Azdo, but running into some issues. Currently the build fails [here](https://compositional-it.visualstudio.com/SAFE%20Template/_build/results?buildId=3191). The error seems to occur on the following build:

```
Failed after 11 tests. Parameters:
	{Server = Some "suave";
 Deploy = Some "gcp-appengine";
 Layout = Some "fulma-landing";
 JsDeps = None;
 Communication = None;
 Pattern = None;}
Shrunk 2 times to:
	{Server = None;
 Deploy = Some "gcp-appengine";
 Layout = None;
 JsDeps = None;
 Communication = None;
 Pattern = None;}
Result:
	Exception
  System.Exception: Process exit code '1' <> 0. Command Line: /home/vsts/.dotnet/tools/fake build
   at Fake.Core.CreateProcess.ensureExitCode@523.Invoke(a data, Int32 exitCode)
   at Fake.Core.CreateProcess.addOnExited@499-5.Invoke(RawProcessResult _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at SAFE.Tests.run(String exe, String arg, String dir) in /home/vsts/work/1/s/tests/Tests.fs:line 166
   at SAFE.Tests.tests@262.Invoke(TemplateArgs x) in /home/vsts/work/1/s/tests/Tests.fs:line 274
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)
Focus on error:
	etestPropertyWithConfig (1222540097, 296618187) &quot;Project should build properly&quot;‌5m ‌4m&lt;‌5mExpecto‌4m&gt;‌5m‌
4m[‌5m11:41:03 ‌5mINF‌4m] ‌5mEXPECTO! ‌1‌5m tests run in ‌00:21:19.2972537‌5m for ‌Project created from template‌5m – ‌0‌5m passed, ‌0‌5m ignored, ‌1‌5m failed, ‌0‌5m errored. ‌5m ‌4m&lt;‌5mExpecto‌4m&gt;‌5m‌
Finished (Failed) &#x27;Tests&#x27; in 00:21:37.7664230‌
```

As it turns out, I tried a gcp-appengine build locally and it actually did fail:

```
> dotnet new safe -d gcp-appengine
The template "SAFE-Stack Web App v1.11.1" was created successfully.

> fake build                                                                                                                                                                                 
Extracted Paket.Restore.targets to: C:\Users\Isaac\Source\Repos\deletemeplz\.paket\Paket.Restore.targets                                                                                     
Starting full restore process.                                                                                                                                                               
Script reported an error:                                                                                                                                                                    
-> gcloud.cmd was not found in path. Please install it and make sure it's available from your path. See https://safe-stack.github.io/docs/quickstart/#install-pre-requisites for more info   

Script reported an error:
-> gcloud.cmd was not found in path. Please install it and make sure it's available from your path. See https://safe-stack.github.io/docs/quickstart/#install-pre-requisites for more info
```

Looking at the pre-requisites link I couldn't find anything about GCP. Is this a real error, or just a coincidence that Devops and and my machine are failing for this build?

**Comment by theimowski** [comment]
Interesting that Travis doesn't fail for same reason - @mastoj do you think gcloud may be preinstalled in the Travis environment?

Anyway, pushed 893550ab0c3c53d7dbcefeff8ac6a77a729ce29d so that gcloud is not checked until one actually wants to run gcloud-specific target

**Comment by mastoj** [comment]
I don’t understand why it works on Travis, I guess it might have gcloud installed. But reading this SO question from 2016 it seems it doesn’t https://stackoverflow.com/questions/38762590/how-to-install-google-cloud-sdk-on-travis

**Comment by isaacabraham** [comment]
Works! 
![image](https://user-images.githubusercontent.com/1781813/61530863-9281c200-aa25-11e9-8a82-cc845bb8c369.png)

**Comment by isaacabraham** [comment]
I guess next steps is if we want to take this any further e.g. working with devops releases (maybe not - that's all done through github already?).

**Comment by theimowski** [comment]
I think we're good for now

**Comment by mastoj** [comment]
Good. Just let me know and I’ll try to help between changing diapers on
twins:)
