### ISSUE TITLE
Error on client side (Webpack) with clean install of a new SAFE project

### ISSUE THREAD

**Issue by ValDY69** [SAFE-Stack/SAFE-template#544]
Hello and thx for this template , i have a problem when i try to create a SAFE project with latest version 4.2.0 (same with 4.1.1) , i just create the project with dotnet new SAFE and after dotnet tool restore i run the dotnet run command and this is the complete output : 

```
PS D:\F#\FsharpWithSafeTest> dotnet run
run Run
Building project with version: LocalBuild
Shortened DependencyGraph for Target Run:
<== Run
   <== InstallClient
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - InstallClient
Group - 3
  - Run
Starting target 'Clean'
D:\F#\FsharpWithSafeTest\src\Client> "dotnet" fable clean --yes (In: false, Out: false, Err: false)
Fable: F# to JS compiler 3.7.5
Stop Russian aggression against Ukraine!

This will recursively delete all *.fs.js[.map] files in D:\F#\FsharpWithSafeTest\src\Client
Deleted output\fable_modules
Clean completed! Files deleted: 0
Finished (Success) 'Clean' in 00:00:00.4314039
Starting target 'InstallClient'
.> "C:\Program Files\nodejs\npm.CMD" install (In: false, Out: false, Err: false)
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

up to date, audited 430 packages in 870ms

56 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Finished (Success) 'InstallClient' in 00:00:01.7604407
Starting target 'Run'
D:\F#\FsharpWithSafeTest\src\Shared> "dotnet" build (In: false, Out: false, Err: false)
MSBuild version 17.3.2+561848881 for .NET
  Identification des projets à restaurer...
  Paket version 7.0.2+a704d681f4688c094e60d2b0795913896f145865
  Restoring D:\F#\FsharpWithSafeTest\src\Shared\Shared.fsproj
  Starting restore process.
  Total time taken: 0 milliseconds
  Tous les projets sont à jour pour la restauration.
  Paket version 7.0.2+a704d681f4688c094e60d2b0795913896f145865
  Restoring D:\F#\FsharpWithSafeTest\src\Shared\Shared.fsproj
  Starting restore process.
  Total time taken: 0 milliseconds
  Shared -> D:\F#\FsharpWithSafeTest\src\Shared\bin\Debug\net6.0\Shared.dll

La génération a réussi.
    0 Avertissement(s)
    0 Erreur(s)

Temps écoulé 00:00:02.09
server: D:\F#\FsharpWithSafeTest\src\Server> dotnet watch run
client: D:\F#\FsharpWithSafeTest\src\Client> dotnet fable watch -o output -s --run npm run start
D:\F#\FsharpWithSafeTest\src\Server> "dotnet" watch run (In: false, Out: true, Err: true)
D:\F#\FsharpWithSafeTest\src\Client> "dotnet" fable watch -o output -s --run npm run start (In: false, Out: true, Err: true)
server: dotnet watch ?? Started
client: Fable: F# to JS compiler 3.7.5
client: Stop Russian aggression against Ukraine!
client: Parsing Client.fsproj...
client: .> cmd /C dotnet restore Client.fsproj
client:   Identification des projets � restaurer...
client:   Paket version 7.0.2+a704d681f4688c094e60d2b0795913896f145865
client:   Restoring D:\F#\FsharpWithSafeTest\src\Shared\Shared.fsproj
client:   Starting restore process.
client:   Total time taken: 0 milliseconds
client:   Tous les projets sont � jour pour la restauration.
client: Some Nuget packages contain information about NPM dependencies that can be managed by Femto: https://github.com/Zaid-Ajaj/Femto
client: Project and references (120 source files) parsed in 3237ms
client: Loaded Feliz.HookAttribute from C:\Users\valen\.nuget\packages\feliz.compilerplugins\1.8.0\lib\netstandard2.0\Feliz.CompilerPlugins.dll
client: Loaded Feliz.ReactComponentAttribute from C:\Users\valen\.nuget\packages\feliz.compilerplugins\1.8.0\lib\netstandard2.0\Feliz.CompilerPlugins.dll
client: Loaded Feliz.ReactMemoComponentAttribute from C:\Users\valen\.nuget\packages\feliz.compilerplugins\1.8.0\lib\netstandard2.0\Feliz.CompilerPlugins.dll
client: Started Fable compilation...
server: info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
server:       User profile is available. Using 'C:\Users\valen\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
server: info: Microsoft.Hosting.Lifetime[14]
server:       Now listening on: http://localhost:5000
server: info: Microsoft.Hosting.Lifetime[0]
server:       Application started. Press Ctrl+C to shut down.
server: info: Microsoft.Hosting.Lifetime[0]
server:       Hosting environment: Development
server: info: Microsoft.Hosting.Lifetime[0]
server:       Content root path: D:\F#\FsharpWithSafeTest\src\Server
client: Fable compilation finished in 6433ms
client: .> cmd /C npm run start
client: Watching ..
client: npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
client: > start
client: > webpack-dev-server --mode development
client: Bundling for run - development ...
client: <i> [webpack-dev-server] [HPM] Proxy created: /api/**  -> http://localhost:5000
client: <i> [webpack-dev-server] [HPM] Proxy created: /socket/**  -> http://localhost:5000
client: <i> [webpack-dev-server] Project is running at:
client: <i> [webpack-dev-server] Loopback: http://localhost:8080/
client: <i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.95:8080/
client: <i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::99cd:5da3:6bec:1204]:8080/
client: <i> [webpack-dev-server] Content not from webpack is served from 'D:\F#\FsharpWithSafeTest\src\Client\public' directory
client: <i> [webpack-dev-server] 404s will fallback to '/index.html'
client: asset runtime.js 41.2 KiB [emitted] (name: runtime)
client: asset index.html 9.26 KiB [emitted]
client: asset app.js 5.14 KiB [emitted] (name: app)
client: Entrypoint app 46.3 KiB = runtime.js 41.2 KiB app.js 5.14 KiB
client: runtime modules 27.1 KiB 9 modules
client: modules with errors 78 bytes [errors]
client:   ../../F#/FsharpWithSafeTest/node_modules/webpack/hot/dev-server.js 39 bytes [not cacheable] [built] [code generated] [1 error]
client:   ../../F#/FsharpWithSafeTest/src/Client/output/App.js 39 bytes [not cacheable] [built] [code generated] [1 error]
client: ERROR in ../../F#/FsharpWithSafeTest/node_modules/webpack/hot/dev-server.js
client: Module build failed (from ../../F#/FsharpWithSafeTest/node_modules/source-map-loader/dist/cjs.js):
client: Error: Cannot find module 'D:\F#\FsharpWithSafeTest\node_modules\source-map-loader\dist\cjs.js'
client: Require stack:
client: - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js
client: - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModuleFactory.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compiler.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\webpack.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\index.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\webpack-cli.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\bootstrap.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\bin\cli.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\bin\webpack-dev-server.js
client:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
client:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
client:     at Module.require (node:internal/modules/cjs/loader:1005:19)
client:     at require (node:internal/modules/cjs/helpers:102:18)
client:     at loadLoader (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js:19:17)
client:     at iteratePitchingLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
client:     at runLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
client:     at NormalModule._doBuild (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModule.js:812:3)
client:     at NormalModule.build (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModule.js:956:15)
client:     at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compilation.js:1367:12
client: ERROR in ../../F#/FsharpWithSafeTest/src/Client/output/App.js
client: Module build failed (from ../../F#/FsharpWithSafeTest/node_modules/source-map-loader/dist/cjs.js):
client: Error: Cannot find module 'D:\F#\FsharpWithSafeTest\node_modules\source-map-loader\dist\cjs.js'
client: Require stack:
client: - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js
client: - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModuleFactory.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compiler.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\webpack.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\index.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\webpack-cli.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\bootstrap.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\bin\cli.js
client: - D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\bin\webpack-dev-server.js
client:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
client:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
client:     at Module.require (node:internal/modules/cjs/loader:1005:19)
client:     at require (node:internal/modules/cjs/helpers:102:18)
client:     at loadLoader (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js:19:17)
client:     at iteratePitchingLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
client:     at runLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
client:     at NormalModule._doBuild (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModule.js:812:3)
client:     at NormalModule.build (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModule.js:956:15)
client:     at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compilation.js:1367:12
client: ERROR in Module not found: Error: Can't resolve 'D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\client\index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&reconnect=10' in 'D:\F#\FsharpWithSafeTest'
client: ERROR in   Error: Child compilation failed:
client:   Module build failed (from ../../F#/FsharpWithSafeTest/node_modules/html-webpa  ck-plugin/lib/loader.js):
client:   Error: Cannot find module 'D:\F#\FsharpWithSafeTest\node_modules\html-webpack  -plugin\lib\loader.js'
client:   Require stack:
client:   - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModuleFactory.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compiler.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\webpack.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\index.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\webpack-cli.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\bootstrap.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\bin\cli.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\bin\webpack-dev-ser  ver.js
client:       at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:  15)
client:       at Function.Module._load (node:internal/modules/cjs/loader:778:27)
client:       at Module.require (node:internal/modules/cjs/loader:1005:19)
client:       at require (node:internal/modules/cjs/helpers:102:18)
client:       at loadLoader (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loa  dLoader.js:19:17)
client:       at iteratePitchingLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-ru  nner\lib\LoaderRunner.js:182:2)
client:       at runLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\Loa  derRunner.js:397:2)
client:       at NormalModule._doBuild (D:\F#\FsharpWithSafeTest\node_modules\webpack\li  b\NormalModule.js:812:3)
client:       at NormalModule.build (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\N  ormalModule.js:956:15)
client:       at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compilation.js:1367:1  2
client:   ModuleBuildError: Module build failed (from ../../F#/FsharpWithSafeTest/node_  modules/html-webpack-plugin/lib/loader.js):
client:   Error: Cannot find module 'D:\F#\FsharpWithSafeTest\node_modules\html-webpack  -plugin\lib\loader.js'
client:   Require stack:
client:   - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModuleFactory.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compiler.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\webpack.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\index.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\webpack-cli.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\bootstrap.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\bin\cli.js
client:   - D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\bin\webpack-dev-ser  ver.js
client:       at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:  15)
client:       at Function.Module._load (node:internal/modules/cjs/loader:778:27)
client:       at Module.require (node:internal/modules/cjs/loader:1005:19)
client:       at require (node:internal/modules/cjs/helpers:102:18)
client:       at loadLoader (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loa  dLoader.js:19:17)
client:       at iteratePitchingLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-ru  nner\lib\LoaderRunner.js:182:2)
client:       at runLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\Loa  derRunner.js:397:2)
client:       at NormalModule._doBuild (D:\F#\FsharpWithSafeTest\node_modules\webpack\li  b\NormalModule.js:812:3)
client:       at NormalModule.build (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\N  ormalModule.js:956:15)
client:       at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compilation.js:1367:1  2
client:       at processResult (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Normal  Module.js:751:19)
client:       at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModule.js:853:5      at D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js  :399:11
client:       at D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js  :185:11
client:       at loadLoader (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loa  dLoader.js:33:11)
client:       at iteratePitchingLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-ru  nner\lib\LoaderRunner.js:182:2)
client:       at runLoaders (D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\Loa  derRunner.js:397:2)
client:       at NormalModule._doBuild (D:\F#\FsharpWithSafeTest\node_modules\webpack\li  b\NormalModule.js:812:3)
client:       at NormalModule.build (D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\N  ormalModule.js:956:15)
client:       at D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compilation.js:1367:1  2
client:
client:   - loader:933 Function.Module._resolveFilename
client:     node:internal/modules/cjs/loader:933:15
client:
client:   - loader:778 Function.Module._load
client:     node:internal/modules/cjs/loader:778:27
client:
client:   - loader:1005 Module.require
client:     node:internal/modules/cjs/loader:1005:19
client:
client:   - helpers:102 require
client:     node:internal/modules/cjs/helpers:102:18
client:
client:   - loadLoader.js:19 loadLoader
client:     [FsharpWithSafeTest]/[loader-runner]/lib/loadLoader.js:19:17
client:
client:   - LoaderRunner.js:182 iteratePitchingLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:182:2
client:
client:   - LoaderRunner.js:397 runLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:397:2
client:
client:   - NormalModule.js:812 NormalModule._doBuild
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:812:3
client:
client:   - NormalModule.js:956 NormalModule.build
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:956:15
client:
client:   - Compilation.js:1367
client:     [FsharpWithSafeTest]/[webpack]/lib/Compilation.js:1367:12
client:
client:   - ModuleBuildError: Module build failed (from ../../F#/FsharpWithSafeTest/nod    e_modules/html-webpack-plugin/lib/loader.js):
client:
client:   - Error: Cannot find module 'D:\F#\FsharpWithSafeTest\node_modules\html-webpa    ck-plugin\lib\loader.js'
client:
client:   - Require stack:
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\loadLoader.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\loader-runner\lib\LoaderRunner.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\NormalModuleFactory.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\Compiler.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\webpack.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack\lib\index.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\webpack-cli.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\lib\bootstrap.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack-cli\bin\cli.js
client:
client:   - - D:\F#\FsharpWithSafeTest\node_modules\webpack-dev-server\bin\webpack-dev-s    erver.js
client:
client:   - loader:933 Function.Module._resolveFilename
client:     node:internal/modules/cjs/loader:933:15
client:
client:   - loader:778 Function.Module._load
client:     node:internal/modules/cjs/loader:778:27
client:
client:   - loader:1005 Module.require
client:     node:internal/modules/cjs/loader:1005:19
client:
client:   - helpers:102 require
client:     node:internal/modules/cjs/helpers:102:18
client:
client:   - loadLoader.js:19 loadLoader
client:     [FsharpWithSafeTest]/[loader-runner]/lib/loadLoader.js:19:17
client:
client:   - LoaderRunner.js:182 iteratePitchingLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:182:2
client:
client:   - LoaderRunner.js:397 runLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:397:2
client:
client:   - NormalModule.js:812 NormalModule._doBuild
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:812:3
client:
client:   - NormalModule.js:956 NormalModule.build
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:956:15
client:
client:   - Compilation.js:1367
client:     [FsharpWithSafeTest]/[webpack]/lib/Compilation.js:1367:12
client:
client:   - NormalModule.js:751 processResult
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:751:19
client:
client:   - NormalModule.js:853
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:853:5
client:
client:   - LoaderRunner.js:399
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:399:11
client:
client:   - LoaderRunner.js:185
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:185:11
client:
client:   - loadLoader.js:33 loadLoader
client:     [FsharpWithSafeTest]/[loader-runner]/lib/loadLoader.js:33:11
client:
client:   - LoaderRunner.js:182 iteratePitchingLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:182:2
client:
client:   - LoaderRunner.js:397 runLoaders
client:     [FsharpWithSafeTest]/[loader-runner]/lib/LoaderRunner.js:397:2
client:
client:   - NormalModule.js:812 NormalModule._doBuild
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:812:3
client:
client:   - NormalModule.js:956 NormalModule.build
client:     [FsharpWithSafeTest]/[webpack]/lib/NormalModule.js:956:15
client:
client:   - Compilation.js:1367
client:     [FsharpWithSafeTest]/[webpack]/lib/Compilation.js:1367:12
client:
client:   - child-compiler.js:169
client:     [FsharpWithSafeTest]/[html-webpack-plugin]/lib/child-compiler.js:169:18
client:
client:   - Compiler.js:559
client:     [FsharpWithSafeTest]/[webpack]/lib/Compiler.js:559:11
client:
client:   - Compiler.js:1129
client:     [FsharpWithSafeTest]/[webpack]/lib/Compiler.js:1129:17
client:
client:
client:   - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
client:     [FsharpWithSafeTest]/[tapable]/lib/Hook.js:18:14
client:
client:   - Compiler.js:1125
client:     [FsharpWithSafeTest]/[webpack]/lib/Compiler.js:1125:33
client:
client:   - Compilation.js:2782 finalCallback
client:     [FsharpWithSafeTest]/[webpack]/lib/Compilation.js:2782:11
client:
client:   - Compilation.js:3087
client:     [FsharpWithSafeTest]/[webpack]/lib/Compilation.js:3087:11
client:
client:
client: 1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
client: 1 error has detailed information that is not shown.
client: Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
client: webpack 5.65.0 compiled with 5 errors in 861 ms
```

i precise that i am on .net core 6 (version sdk 6.0.403) and i try with many version of node (16.X and 18.X) and same error
a have this error when i try to access to the website (localhost:8080) : 

![image](https://user-images.githubusercontent.com/34503404/206853273-992a8da0-a61d-4744-b740-b14ec51bbab9.png)

i also precise that i am on windows
do you have any ideas why i have this error on a fresh created project ? 

Thx,
Valentin

**Comment by theprash** [comment]
@ValDY69 Thanks for reporting this. It looks like the issue is caused by the fact that you have a `#` in your project path: `D:\F#\FsharpWithSafeTest`. I was able to reproduce this issue on Windows. I've noticed this sort of thing before where some tools don't like this character in a path, so it's best to avoid it as much as possible.
