### ISSUE TITLE
unable to download dotnet sdk

### ISSUE THREAD

**Issue by peltco** [SAFE-Stack/SAFE-template#69]
If i follow the steps  here
https://safe-stack.github.io/docs/quickstart/

It seems to give an error on the following step
Downloading 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.3/dotnet-dev-win-x64.2.1.3.zip' to ...

The error message i see is
Running build failed.
Error:
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in D:\code\fake\src\app\FakeLib\ZipHelper.fs:line 89
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 561
   at FSI_0005.Build.clo@35-2.Invoke(Unit _arg2)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

This seems to be because the file seems to be gone from azureedge.

I'm unsure how to edit my source/template to point to a valid file

**Comment by theimowski** [comment]
I'll update the sdk to the newest version, meanwhile can you try removing the file in tmp directory that the scirpt is trying to download to? Had exactly the same issue, and removing solved it

**Comment by peltco** [comment]
changing global.json worked
