### ISSUE TITLE
build.cmd fails

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-template#85]
```
Performance:
 - Disk IO: 18 milliseconds
 - Runtime: 1 second
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== InstallClient
      <== InstallDotNetCore
         <== Clean

The running order is:
  - Clean
  - InstallDotNetCore
  - InstallClient
  - Build
Running build with 1 worker
Starting Target: Clean
Deleting contents of C:\Users\vaskir\git\Safe1\deploy
Finished Target: Clean
Starting Target: InstallDotNetCore (==> Clean)
dotnet --info
C:\Users\vaskir\AppData\Local\dotnetcore\dotnet.exe --info
C:\Users\vaskir\AppData\Local\dotnetcore\dotnet.exe --version
Deleting contents of C:\Users\vaskir\AppData\Local\dotnetcore
Downloading 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.105/dotnet-dev-win-x64.2.1.105.zip' to 'C:\Users\vaskir\AppData\Local\Temp\dotnet-dev-win-x64.2.1.105.zip'
Running build failed.
Error:
ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in D:\code\fake\src\app\FakeLib\ZipHelper.fs:line 89
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 567
   at FSI_0005.Build.clo@31-2.Invoke(Unit _arg2) in C:\Users\vaskir\git\Safe1\build.fsx:line 32
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0023418
InstallDotNetCore   Failure
Total:              00:00:01.2442080
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in D:\code\fake\src\app\FakeLib\ZipHelper.fs:line 89
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\fake\src\app\FakeLib\DotNetCLIHelper.fs:line 567
   at FSI_0005.Build.clo@31-2.Invoke(Unit _arg2) in C:\Users\vaskir\git\Safe1\build.fsx:line 32
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------
```

**Comment by vasily-kirichenko** [comment]
After deleting half-downloaded zip file, everything seems ok.
